import Head from 'next/head'
import { useState, useCallback, useEffect } from 'react'
import Script from 'next/script'
import { 
  SparklesIcon, 
  CameraIcon,
  SwatchIcon,
  LightBulbIcon,
  StarIcon 
} from '@heroicons/react/24/solid'
import Image from 'next/image'
import ImageUpload from '../components/ImageUpload'
import Link from 'next/link'
import { analytics, trackConversion, setUserProperties } from '../utils/analytics'
import { safeSetItem } from '../utils/localStorage'

const features = [
  {
    name: 'Virtual Try-On',
    description: 'See exactly how clothes look on you with our advanced AI technology - just like trying them on in a real fitting room.',
    icon: CameraIcon,
  },
  {
    name: 'AI Style Generation',
    description: 'Get complete outfit ideas generated by AI based on your style preferences and current wardrobe.',
    icon: SparklesIcon,
  },
  {
    name: 'Smart Style Recommendations',
    description: 'Receive personalized daily outfit suggestions that match your style, occasion, and weather.',
    icon: LightBulbIcon,
  },
  {
    name: 'Mix & Match',
    description: 'Experiment with different combinations from your wardrobe to create perfect outfits for any occasion.',
    icon: SwatchIcon,
  },
]

const testimonials = [
  {
    content: "The AI try-on feature is incredibly accurate! I can see exactly how clothes will look on me before buying.",
    author: "Sarah Johnson",
    role: "Fashion Enthusiast",
    rating: 5,
  },
  {
    content: "The AI-generated outfit combinations are amazing. It's like having a personal stylist who knows my taste perfectly.",
    author: "Michael Chen",
    role: "Young Professional",
    rating: 5,
  },
  {
    content: "Daily style recommendations are spot-on! It saves me so much time deciding what to wear each morning.",
    author: "Emma Williams",
    role: "Content Creator",
    rating: 5,
  },
]

export default function Home() {
  const [modelImage, setModelImage] = useState<File | null>(null)
  const [clothingImage, setClothingImage] = useState<File | null>(null)
  const [resultImage, setResultImage] = useState<string | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  // 页面加载时记录访问
  useEffect(() => {
    analytics.seo.organic_landing('home')
    setUserProperties({
      page_type: 'landing_page',
      user_segment: 'new_visitor'
    })
  }, [])



  const handleGenerate = useCallback(async () => {
    if (!modelImage || !clothingImage) {
      setError('Please upload a model photo and a clothing photo');
      analytics.performance.error_occurred('missing_images', 'virtual_tryon')
      return;
    }

    // 跟踪虚拟试衣开始
    analytics.virtualTryOn.start()
    analytics.virtualTryOn.generate_start()
    
    setLoading(true);
    setError(null);

    try {
      // 创建支付会话
      const paymentResponse = await fetch('/api/create-payment', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        }
      });

      if (!paymentResponse.ok) {
        throw new Error('Failed to create payment session');
      }

      const { url: paymentUrl } = await paymentResponse.json();
      
      // 将图片数据存储在 localStorage 中
      const modelBase64 = await fileToBase64(modelImage);
      const clothingBase64 = await fileToBase64(clothingImage);
      
      // 使用安全的 localStorage 操作
      console.log('Saving images to storage...');
      console.log('Model image size:', modelBase64.length, 'chars');
      console.log('Clothing image size:', clothingBase64.length, 'chars');
      
      const modelSaved = safeSetItem('modelImage', modelBase64);
      const clothingSaved = safeSetItem('clothingImage', clothingBase64);
      
      console.log('Save results - Model:', modelSaved, 'Clothing:', clothingSaved);
      
      if (!modelSaved || !clothingSaved) {
        console.error('Failed to save images to localStorage');
        analytics.performance.error_occurred('localStorage_error', 'virtual_tryon')
      } else {
        console.log('Images successfully saved to storage');
      }
      
      // 保存时间戳，用于验证数据新鲜度
      const timestamp = Date.now().toString();
      safeSetItem('imageUploadTimestamp', timestamp);
      console.log('Saved timestamp:', timestamp);
      
      // 跟踪支付页面跳转
      trackConversion('payment_redirect')
      analytics.user.upgrade('virtual_tryon_service')
      
      // 重定向到支付页面
      window.location.href = paymentUrl;

    } catch (err) {
      console.error('Payment error:', err);
      const errorMessage = err instanceof Error ? err.message : 'Payment failed, please try again'
      setError(errorMessage);
      
      // 跟踪支付错误
      analytics.virtualTryOn.generate_error(errorMessage)
      analytics.user.payment_failed(errorMessage)
    } finally {
      setLoading(false);
    }
  }, [modelImage, clothingImage]);

  // 处理图片上传的分析跟踪
  const handleModelImageUpload = (file: File | null) => {
    setModelImage(file)
    if (file) {
      analytics.virtualTryOn.upload_person()
    }
  }

  const handleClothingImageUpload = (file: File | null) => {
    setClothingImage(file)
    if (file) {
      analytics.virtualTryOn.upload_clothes()
    }
  }

  // 将 fileToBase64 移到组件外部
  const fileToBase64 = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.readAsDataURL(file)
      reader.onload = () => resolve(reader.result as string)
      reader.onerror = error => reject(error)
    })
  }

  // 将结构化数据移到组件外部
  const structuredData = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    "name": "DressMeAI",
    "description": "AI-powered virtual try-on and style recommendation platform",
    "applicationCategory": "Fashion & Style",
    "operatingSystem": "Web Browser",
    "offers": {
      "@type": "Offer",
      "price": "0",
      "priceCurrency": "USD"
    },
    "featureList": [
      "Virtual Try-On",
      "AI Style Generation",
      "Smart Style Recommendations",
      "Mix & Match"
    ],
    "aggregateRating": {
      "@type": "AggregateRating",
      "ratingValue": "5",
      "ratingCount": "3",
      "reviewCount": "3"
    }
  }

  return (
    <div className="container mx-auto px-4">
      <div className="flex justify-between items-center py-4 mb-8">
        <h1 className="text-4xl font-bold">AI FASHION</h1>
        <nav>
          <div className="space-x-6">
            <Link 
              href="/history" 
              className="text-blue-600 hover:text-blue-800 transition-colors"
              onClick={() => analytics.navigation.internal_link_click('/history')}
            >
              History
            </Link>
            <Link 
              href="/blog" 
              className="text-blue-600 hover:text-blue-800 transition-colors"
              onClick={() => analytics.navigation.internal_link_click('/blog')}
            >
              Blog
            </Link>
          </div>
        </nav>
      </div>
      
      <h2 className="text-3xl font-bold mb-8 text-center">Virtual Try-On Technology - See How Clothes Look on Your Body</h2>
      
      <Head>
        <title>Virtual Try-On AI Fashion App | DressMeAI - See How Clothes Look on You</title>
        <meta name="description" content="Try on clothes virtually with DressMeAI's AI-powered fashion app. See how outfits look on you instantly, get personalized style recommendations, and shop with confidence. Virtual fitting room - start now!" />
        <meta name="keywords" content="virtual try-on, try on clothes online, AI fashion app, virtual fitting room, outfit generator, fashion styling app, virtual wardrobe, AI style assistant, clothes simulator, fashion technology, virtual clothes fitting, AI virtual try-on, personal stylist AI, digital wardrobe" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        
        {/* Favicon and App Icons */}
        <link rel="icon" href="/icons/favicon.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/icons/apple-touch-icon.png" />
        <link rel="icon" type="image/png" sizes="32x32" href="/icons/favicon.ico" />
        <link rel="icon" type="image/png" sizes="192x192" href="/icons/icon-192.png" />
        <link rel="icon" type="image/png" sizes="512x512" href="/icons/icon-512.png" />
        
        {/* PWA Settings */}
        <meta name="application-name" content="DressMeAI" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="default" />
        <meta name="apple-mobile-web-app-title" content="DressMeAI" />
        <meta name="mobile-web-app-capable" content="yes" />
        <meta name="msapplication-TileColor" content="#4F46E5" />
        <meta name="msapplication-tap-highlight" content="no" />
        <meta name="theme-color" content="#4F46E5" />

        <link rel="canonical" href="https://dressmeai.com" />
        
        {/* Language and Region */}
        <meta property="og:locale" content="en_US" />
        <meta property="og:locale:alternate" content="zh_CN" />
        
        {/* Open Graph / Facebook */}
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="DressMeAI" />
        <meta property="og:title" content="Virtual Try-On AI Fashion App | DressMeAI - See How Clothes Look on You" />
        <meta property="og:description" content="Try on clothes virtually with DressMeAI's AI-powered fashion app. See how outfits look on you instantly, get personalized style recommendations, and shop with confidence." />
        <meta property="og:image" content="https://dressmeai.com/images/og-banner.jpg" />
        <meta property="og:url" content="https://dressmeai.com" />
        
        {/* Twitter */}
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@dressmeai" />
        <meta name="twitter:creator" content="@dressmeai" />
        <meta name="twitter:title" content="Virtual Try-On AI Fashion App | DressMeAI - See How Clothes Look on You" />
        <meta name="twitter:description" content="Try on clothes virtually with DressMeAI's AI-powered fashion app. See how outfits look on you instantly, get personalized style recommendations, and shop with confidence." />
        <meta name="twitter:image" content="https://dressmeai.com/images/og-banner.jpg" />
        
        {/* Additional SEO Meta Tags */}
        <meta name="robots" content="index, follow" />
        <meta name="author" content="DressMeAI Team" />
      </Head>

      {/* 添加结构化数据 */}
      <Script
        id="structured-data"
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
      />

      <main>
        {/* Hero Section */}
        <section className="relative px-4 sm:px-6 lg:px-8 py-20 sm:py-28">
          <div className="mx-auto max-w-5xl">
            <div className="text-center">
              <h1 className="text-5xl sm:text-6xl font-bold tracking-tight text-gray-900 mb-8">
                AI Virtual Try-On<br />
                <span className="bg-gradient-to-r from-indigo-600 to-purple-600 text-transparent bg-clip-text">Your Personal Style Expert</span>
              </h1>
              <p className="text-xl leading-relaxed text-gray-600 max-w-3xl mx-auto">
                Experience clothes virtually before you buy, get AI-curated outfits, and receive daily style recommendations tailored just for you.
              </p>
              <div className="mt-12 flex items-center justify-center gap-x-8">
                <a
                  href="#ai-fashion"
                  className="rounded-lg bg-indigo-600 px-6 py-3 text-base font-semibold text-white shadow-sm hover:bg-indigo-500 transition-colors duration-200"
                >
                  Try On Now
                </a>
                <a href="#features" className="text-base font-semibold leading-6 text-gray-900 hover:text-indigo-600 transition-colors duration-200">
                  Learn More <span aria-hidden="true">→</span>
                </a>
              </div>
            </div>
          </div>
        </section>

        {/* Features Section */}
        <section id="features" className="py-20 sm:py-28 bg-white">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-lg font-semibold leading-8 tracking-wide text-indigo-600 uppercase">AI Fashion Features That Transform Your Shopping Experience</h2>
              <h3 className="mt-3 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
                Your Complete AI Fashion Assistant - Try On, Style & Shop Smarter
              </h3>
              <p className="mt-6 text-xl leading-relaxed text-gray-600">
                From virtual try-ons to personalized style recommendations, our AI technology revolutionizes how you discover and create your perfect look.
              </p>
            </div>
            <div className="mx-auto mt-16 sm:mt-20">
              <dl className="grid grid-cols-1 gap-12 lg:grid-cols-4">
                {features.map((feature) => (
                  <div key={feature.name} className="relative">
                    <dt className="flex items-center gap-x-3 text-lg font-semibold leading-7 text-gray-900">
                      <feature.icon className="h-7 w-7 flex-none text-indigo-600" aria-hidden="true" />
                      {feature.name}
                    </dt>
                    <dd className="mt-4 text-base leading-7 text-gray-600">
                      {feature.description}
                    </dd>
                  </div>
                ))}
              </dl>
            </div>
          </div>
        </section>

        {/* How It Works Section */}
        <section id="how-it-works" className="py-20 sm:py-28 bg-gray-50">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-lg font-semibold leading-8 tracking-wide text-indigo-600 uppercase">How Our AI Virtual Fitting Room Works in 3 Simple Steps</h2>
              <h3 className="mt-3 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
                Begin Your AI Fashion Journey - Upload Photo & Try On Instantly
              </h3>
            </div>
            <div className="mx-auto mt-16 sm:mt-20">
              <div className="grid grid-cols-1 gap-12 lg:grid-cols-3">
                <div className="text-center">
                  <div className="flex justify-center">
                    <CameraIcon className="h-16 w-16 text-indigo-600" />
                  </div>
                  <h4 className="mt-6 text-xl font-semibold text-gray-900">1. Create Your Profile</h4>
                  <p className="mt-4 text-base leading-relaxed text-gray-600">Upload a photo and share your style preferences to personalize your experience.</p>
                </div>
                <div className="text-center">
                  <div className="flex justify-center">
                    <SparklesIcon className="h-16 w-16 text-indigo-600" />
                  </div>
                  <h4 className="mt-6 text-xl font-semibold text-gray-900">2. Explore Styles</h4>
                  <p className="mt-4 text-base leading-relaxed text-gray-600">Browse clothes and let our AI generate perfect outfit combinations for you.</p>
                </div>
                <div className="text-center">
                  <div className="flex justify-center">
                    <LightBulbIcon className="h-16 w-16 text-indigo-600" />
                  </div>
                  <h4 className="mt-6 text-xl font-semibold text-gray-900">3. Get Inspired</h4>
                  <p className="mt-4 text-base leading-relaxed text-gray-600">Receive daily outfit suggestions and try them on virtually with our AI.</p>
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Testimonials Section */}
        <section id="testimonials" className="py-20 sm:py-28 bg-white">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-lg font-semibold leading-8 tracking-wide text-indigo-600 uppercase">What Fashion Lovers Say About DressMeAI Virtual Try-On</h2>
              <h3 className="mt-3 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
                Real Users Share Their Virtual Try-On Success Stories
              </h3>
            </div>
            <div className="mx-auto mt-16 sm:mt-20 grid grid-cols-1 gap-8 lg:grid-cols-3">
              {testimonials.map((testimonial, index) => (
                <div key={index} className="flex flex-col bg-gray-50 p-8 rounded-2xl shadow-sm">
                  <div className="flex gap-x-1 mb-4">
                    {[...Array(testimonial.rating)].map((_, i) => (
                      <StarIcon key={i} className="h-6 w-6 text-yellow-400" aria-hidden="true" />
                    ))}
                  </div>
                  <p className="flex-grow text-lg leading-relaxed text-gray-600">{testimonial.content}</p>
                  <div className="mt-8 border-t border-gray-200 pt-6">
                    <p className="font-semibold text-lg text-gray-900">{testimonial.author}</p>
                    <p className="text-base text-gray-600">{testimonial.role}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* CTA Section */}
        <section id="get-started" className="py-20 sm:py-28 bg-indigo-600">
          <div className="mx-auto max-w-5xl px-4 sm:px-6 lg:px-8">
            <div className="text-center">
              <h2 className="text-4xl font-bold tracking-tight text-white sm:text-5xl">
                Start Your Virtual Try-On Experience Today
              </h2>
              <p className="mx-auto mt-6 max-w-2xl text-xl leading-relaxed text-indigo-100">
                Experience the future of fashion with our AI-powered virtual try-on technology.
              </p>
              <div className="mt-10">
                <button
                  onClick={() => {
                    const tryOnSection = document.getElementById('ai-fashion')
                    tryOnSection?.scrollIntoView({ behavior: 'smooth' })
                    analytics.navigation.internal_link_click('try_virtual_tryon')
                  }}
                  className="rounded-lg bg-white px-8 py-4 text-lg font-semibold text-indigo-600 shadow-sm hover:bg-indigo-50 transition-colors duration-200"
                >
                  Try Virtual Try-On
                </button>
              </div>
            </div>
          </div>
        </section>

        <section id="ai-fashion" className="py-20 sm:py-28 bg-gray-50">
          <div className="mx-auto max-w-6xl px-4 sm:px-6 lg:px-8">
            <div className="mx-auto max-w-3xl text-center">
              <h2 className="text-lg font-semibold leading-8 tracking-wide text-indigo-600 uppercase">Experience AI-Powered Fashion Styling Now</h2>
              <h3 className="mt-3 text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl">
                Virtual Try-On Demo - See the Magic Yourself
              </h3>
            </div>
            <div className="mx-auto mt-16 sm:mt-20">
              <div className="grid md:grid-cols-2 gap-8 mb-8">
                <div>
                  <h4 className="text-xl font-semibold mb-4">Upload Model Photo</h4>
                  <ImageUpload
                    label="Upload a full body photo"
                    onImageSelect={handleModelImageUpload}
                  />
                </div>
                
                <div>
                  <h4 className="text-xl font-semibold mb-4">Upload Clothing Photo</h4>
                  <ImageUpload
                    label="Upload a clothing photo"
                    onImageSelect={handleClothingImageUpload}
                  />
                </div>
              </div>

              <div className="text-center">
                <button
                  onClick={handleGenerate}
                  disabled={loading || !modelImage || !clothingImage}
                  className={`px-6 py-3 rounded-lg text-white font-medium
                    ${loading || !modelImage || !clothingImage
                      ? 'bg-gray-400 cursor-not-allowed'
                      : 'bg-blue-600 hover:bg-blue-700'
                    }`}
                >
                  {loading ? 'Generating...' : 'Generate'}
                </button>

                {error && (
                  <p className="mt-4 text-red-500">{error}</p>
                )}
              </div>

              {resultImage && (
                <div className="mt-8">
                  <h4 className="text-xl font-semibold mb-4">Result</h4>
                  <div className="relative w-full h-96">
                    <Image
                      src={resultImage}
                      alt="Try-on Result"
                      fill
                      className="object-contain rounded-lg"
                    />
                  </div>
                </div>
              )}
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}